#!/usr/bin/env python3
"""Generate the idealized ridge terrain for FireRidgeLineAdvective34deg,
ROTATED so the ridge crest is PERPENDICULAR to this case's 34deg wind
bearing (head-on incidence, same as the 90deg case's NS ridge vs its
due-east wind) instead of a fixed north-south crest hit by an oblique
34deg wind.

Originally this directory used WRF-Fire's fire_mountain_type=3 formula
unmodified (crest fixed north-south, height varying with domain x only):
that made the 34deg case a genuinely different physical problem from the
90deg case (near-grazing flow along an infinite ridge, not a rotated
version of the same head-on-incidence problem) -- WRF's companion run at
that fixed orientation blew up (NaN, w-cfl up to 3.9) at t=1597s, a real
grazing-incidence instability, not a bug. Rotating the ridge itself
instead of the wind restores the same "rotate the whole problem, wind
stays head-on" symmetry the hill cases have (a hill is radially
symmetric, so any wind bearing is an equivalent, just-rotated problem);
a straight ridge needs the terrain rotated along with the wind bearing to
get that same equivalence.

Formula: project (x,y) onto the wind-bearing axis before evaluating the
original clamped-cosine profile:

    s(x,y) = (x-cx)*sin(theta) + (y-cy)*cos(theta) + cx
    mtn_s  = pi + 2*pi * clamp((s - x_start)/(x_end - x_start), 0, 1)
    z(x,y) = height * 0.5 * (1 + cos(mtn_s))

theta=90 (compass bearing, matching the wind-vector convention
w=(sin theta, cos theta)) reduces s to x exactly, reproducing the
original NS-ridge formula used by the 90deg case -- so this is a strict
generalization, not a different model. theta=34 here rotates the crest to
be perpendicular to this case's own 34deg wind.

Same height/x-footprint convention as FireHillLineAdvective's hill
(fire_mountain_type=1): height 300 m, half-width 1000 m in the projected
coordinate (crest at s=2500), so the two terrain families are directly
comparable. WRF's companion case
(case_ridge_line_advective_34deg/namelist.input) uses the equivalent
file-based terrain input (fire_mountain_type=0, fire_read_atm_ht/
fire_read_fire_ht=.true., input_ht/input_zsf generated by
gen_wrf_rotated_ridge.py with the identical s(x,y) formula) since WRF's
own fire_mountain_type formulas only support axis-aligned ridges.

Writes two files in the ERF_FireTerrainReader.H raster format (nx, ny,
x-coords, y-coords, z-values row-major with x outer / y inner):

  terrain_atm.txt   100 m spacing (53x53), for erf.terrain_file_name
  terrain_fire.txt   25 m spacing (209x209), for erf.fire.terrain_file_name

Domain side 5200 m, same reasoning as FireHillLineAdvective's gen_hill_terrain.py
(grid_ratio=4 divisibility).
"""
import math

L = 5200.0            # domain side [m]
HEIGHT = 300.0         # ridge height [m]
X_START, X_END = 1500.0, 3500.0    # ridge half-width 1000m in the projected coordinate
CX, CY = 2500.0, 2500.0
THETA_DEG = 34.0        # this case's wind bearing -- ridge crest is rotated perpendicular to it

_TH = math.radians(THETA_DEG)
_SIN_T, _COS_T = math.sin(_TH), math.cos(_TH)


def ridge_z(x, y):
    s = (x - CX) * _SIN_T + (y - CY) * _COS_T + CX
    fx = max(0.0, min((s - X_START) / (X_END - X_START), 1.0))
    mx = math.pi + 2 * math.pi * fx
    return HEIGHT * 0.5 * (1.0 + math.cos(mx))


def write_raster(fname, dx):
    n = int(round(L / dx)) + 1
    xs = [i * dx for i in range(n)]
    ys = [j * dx for j in range(n)]
    with open(fname, "w") as f:
        f.write(f"{n}\n{n}\n")
        for x in xs:
            f.write(f"{x:.2f}\n")
        for y in ys:
            f.write(f"{y:.2f}\n")
        for x in xs:
            for y in ys:
                f.write(f"{ridge_z(x, y):.4f}\n")
    zmax = max(ridge_z(x, y) for x in xs for y in ys)
    print(f"{fname}: {n}x{n} nodes at dx={dx} m, peak z={zmax:.3f} m")


write_raster("terrain_atm.txt", 100.0)
write_raster("terrain_fire.txt", 25.0)
